bucket:
  name: "my-bucket"

storage:
  path: "/var/lib/sss/data"
  multipart_path: "/var/lib/sss/tmp"

server:
  address: ":8080"

credentials:
  - access_key_id: "AKIAIOSFODNN7EXAMPLE"
    secret_access_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    privileges: "read-write"

  - access_key_id: "AKIAIOSFODNN7READONLY"
    secret_access_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYREADONLY"
    privileges: "read"
